package:
  name: cptextras
  version: "1.2.0"

source:
  path: ..
build:
  number: 0
  noarch: python

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - scipy
    - xarray
    - cartopy
    - matplotlib
    - statsmodels
    - cptio
    - cptdl

test:
  imports:
    - cptextras

about:
  home:
  license: MIT
  summary: "CPT-EXTRAS"
  description: "CPT-EXTRAS"
  dev_url: https://github.com/iri-pycpt/CPT-EXTRAS
