name: pycpt
channels:
  - iri-nextgen
  - conda-forge
dependencies:
  - pycpt=2.5.0

  # cptdl requires python 3.8. This constraint really belongs on
  # cptdl, but I'm not building a new package just to add that
  # constraint.
  - python>=3.8

  # These are dependencies of pycpt, so would be included anyway, but
  # listing them explicitly allows them to be updated with conda lock
  # update. This is a workaround for
  # https://github.com/conda/conda-lock/issues/370
  - cptbin=17.8.3
  - cptcore=2.2.0
  - cptdl=1.1.1
  - cptextras=1.2.0
  - cptio=1.0.4
