package:
  name: pycpt
  version: "2.3.1"

source:
  path: ..

build:
  number: 0
  noarch: python

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - xarray 
    - dask
    - cptio
    - cptdl 
    - cptcore 
    - cptextras>=1.1.0
    - matplotlib<3.7.2  # 3.7.2 gives error in subseasonal.py:plot_forecasts
    - cartopy
    - netcdf4
    - scipy
    - numpy 
    - scikit-learn
    - statsmodels
    - bottleneck
    - jupyter 
    - ipykernel 
    - numpy 
    
    # Temporarily pinning tornado because it seems to fix occasional
    # crashes of the jupyter kernel.  See
    # https://github.com/jupyter/notebook/issues/6721
    - tornado<6.2



test:
  imports:
    - pycpt

about:
  home: https://iri-pycpt.github.io/
  license: MIT
  summary: 'Python Interface to the IRIs Climate Predictability Tool' 
  description: 'CPT'
  dev_url: https://github.com/iri-pycpt/
