from .cca import canonical_correlation_analysis
from .pcr import principal_components_regression
from .deterministic_skill import deterministic_skill
from .probabilistic_forecast_verification import probabilistic_forecast_verification
from .mlr import multiple_regression