package:
  name: cptdl
  version: "1.1.1"

source:
  path: ..

build:
  number: 0
  noarch: python

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - xarray
    - cptio
    - requests

    # requests depends on urllib3; urllib3 v2 removes all the old,
    # unsafe ciphers that are currently supported by the ancient
    # version of squid on iridl.ldeo.columbia.edu, causing all https
    # downloads to fail.
    - urllib3<2

test:
  imports:
    - cptdl



about:
  home: https://github.com/iri-pycpt/
  license: MIT
  summary: 'toolkit bridging the gap between CPT and Xarray'
  description: 'IRI DL Downloads'
  dev_url: https://github.com/iri-pycpt/
