package:
  name: pycpt
  version: "2.9.0"

source:
  path: ..

build:
  number: 2
  noarch: python
  script: "{{ PYTHON }} -m pip install --no-deps ."
  entry_points:
    - generate-forecasts-from-config = pycpt.commands:generate_forecasts
    - upload-forecasts-from-config = pycpt.commands:upload_forecasts

requirements:
  host:
    - python>=3.8
    - pip
    - setuptools
  run:
    # 3.13 changes undefined behavior on which cptdl relies.
    - python>=3.8,<3.13
    - bottleneck
    - cartopy
    - cptbin
    - cptio
    - dask
    - ftputil
    - netcdf4
    - notebook
    - numpy
    - psutil
    - requests
    - scipy
    - statsmodels
    - xarray
    
    # requests depends on urllib3; urllib3 v2 removes all the old,
    # unsafe ciphers that are currently supported by the ancient
    # version of squid on iridl.ldeo.columbia.edu, causing all https
    # downloads to fail.
    - urllib3<2

test:
  imports:
    - cptcore
    - cptcore.functional
    - cptdl
    - cptextras
    - pycpt

about:
  home: https://iri-pycpt.github.io/
  license: MIT
  summary: "Python Interface to the IRI's Climate Predictability Tool"
  description: 'CPT'
  dev_url: https://github.com/iri-pycpt/
