package:
  name: pycpt
  version: "2.8.1"

source:
  path: ..

build:
  number: 0
  noarch: python
  entry_points:
    - generate-forecasts-from-config = pycpt.commands:generate_forecasts
    - upload-forecasts-from-config = pycpt.commands:upload_forecasts

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - bottleneck
    - cartopy
    - cptbin
    - cptdl
    - cptio
    - dask
    - ftputil
    - ipykernel
    - jupyter
    - matplotlib<3.7.2  # 3.7.2 gives error in subseasonal.py:plot_forecasts
    - netcdf4
    - numpy
    - psutil
    - scikit-learn
    - scipy
    - statsmodels
    - xarray
    
    # Temporarily pinning tornado because it seems to fix occasional
    # crashes of the jupyter kernel.  See
    # https://github.com/jupyter/notebook/issues/6721
    - tornado<6.2



test:
  imports:
    - cptcore
    - cptcore.functional
    - cptextras
    - pycpt

about:
  home: https://iri-pycpt.github.io/
  license: MIT
  summary: "Python Interface to the IRI's Climate Predictability Tool"
  description: 'CPT'
  dev_url: https://github.com/iri-pycpt/
