package:
  name: cptio
  version: "1.3.1"

source:
  path: ..

build:
  number: 2
  noarch: python
  script: "{{ PYTHON }} -m pip install --no-deps ."

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - xarray 

test:
  imports:
    - cptio
    - cptio.utilities
    - cptio.fileio
    - cptio.enacts

    

about:
  home: https://github.com/iri-pycpt/
  license: MIT
  summary: 'toolkit bridging the gap between CPT and Xarray' 
  description: 'CPT Xarray Tools & IRI DL Downloads'
  dev_url: https://github.com/iri-pycpt/
